# Site settings
title: Hussein Lezzaik blog
email: 
description: "In pursuit of curious AGIs."
baseurl: ""
url: "http://husseinlezzaik.github.io"
twitter_username: HusseinLezzaik
github_username:  HusseinLezzaik

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
